### ISSUE TITLE
Recieve the ac_id from the relevent paparazzi file 

### ISSUE THREAD

**Issue by Lionfrog** [uaarg/missioncommander#19]
As of now the ac_id (airplane designation on the ivy bus) is hard coded as int(5). This is necessary to send any message across the ivy bus. Ideally we should read this from the relevant airframe file and keep it as a config property, and have the option to change it as a command-line argument. Similar setup to how we treat the flight plan file to get the right waypoints.

**Comment by rijesha** [comment]
@cxiao has suggested that we don't hardcode anything and just listen to messages from the IVY Bus. 

To do that we would need to listen for the Alive message. Once we get an alive message we would then look in /var/generated (maybe) inside that folder there is an md5 hash. 

If the md5 hash is equivalent to what is given in the alive message and the id is the same then we know we have the correct plane. We can also get the flightplan from this folder instead. 

Downside is you can't load all the waypoint on mission commander start up. You will have to wait for the first alive message. (just like the GCS)

**Comment by rijesha** [comment]
This has been sort of fixed with https://github.com/uaarg/missioncommander/commit/172b717f66de5932be0487b35c3875abaa041d36. Proper shutdown does not occur if no xml is available. UI should be independent of mission commander object.
