### ISSUE TITLE
Write Error Checking code for xmlreader

### ISSUE THREAD

**Issue by uaarg** [uaarg/missioncommander#4]
Need to ensure that a proper file is being opened and not errors in parsing. As well the GUI should not allow the selection of files not ending in .xml.

**Comment by Lionfrog** [comment]
I'm not sure what were looking for here... 
 if you try to put a bad xml file as an argument the parser rejects it. 

.../missioncommander$ python3 ./main.py -x badXML
Traceback (most recent call last):
  File "./main.py", line 88, in <module>
    mc = MissionCommander(argDict['flightPlan'])
...
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 585, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/sebastian/UAARG/paparazzi/conf/flight_plans/UAARG/badXML'
